change upload-docs script to use stack.

diff --git a/upload-docs b/upload-docs
--- a/upload-docs
+++ b/upload-docs
@@ -1,46 +1,28 @@
 #!/bin/bash
-set -e
 
-if [ "$#" -ne 1 ]; then
-  echo "Usage: scripts/hackage-docs.sh HACKAGE_USER"
+# Adapted from script by Dimitri Sabadie <dimitri.sabadie@gmail.com>
+
+dist=$(stack path --dist-dir --stack-yaml ./stack.yaml)
+packagename=$(awk '/^name:\s*(.*)/{ print $2 }' ./*.cabal)
+packageversion=$(awk '/^version:\s*(.*)/{ print $2 }' ./*.cabal)
+
+echo -e "\033[1;36mGenerating documentation for $packagename-$packageversion\033[0m"
+
+if ! stack haddock; then
+  echo -e "\033[1;31m'stack haddock failed, are you in a stack project?\033[0m"
   exit 1
 fi
 
-user=$1
-
-cabal_file=$(find . -maxdepth 1 -name "*.cabal" -print -quit)
-if [ ! -f "$cabal_file" ]; then
-  echo "Run this script in the top-level package directory"
-  exit 1
-fi
-
-pkg=$(awk -F ":[[:space:]]*" 'tolower($1)=="name"    { print $2 }' < "$cabal_file")
-ver=$(awk -F ":[[:space:]]*" 'tolower($1)=="version" { print $2 }' < "$cabal_file")
-
-if [ -z "$pkg" ]; then
-  echo "Unable to determine package name"
-  exit 1
-fi
-
-if [ -z "$ver" ]; then
-  echo "Unable to determine package version"
-  exit 1
-fi
-
-echo "Detected package: $pkg-$ver"
-
-dir=$(mktemp -d build-docs.XXXXXX)
-trap 'rm -r "$dir"' EXIT
-
-cabal haddock --hoogle --hyperlink-source --html-location='/package/$pkg-$version/docs' --contents-location='/package/$pkg-$version'
-
-cp -R dist/doc/html/$pkg/ $dir/$pkg-$ver-docs
-
-tar cvz -C $dir --format=ustar -f $dir/$pkg-$ver-docs.tar.gz $pkg-$ver-docs
-
-curl -X PUT \
-     -H 'Content-Type: application/x-tar' \
-     -H 'Content-Encoding: gzip' \
-     -u "$user" \
-     --data-binary "@$dir/$pkg-$ver-docs.tar.gz" \
-     "https://hackage.haskell.org/package/$pkg-$ver/docs"
+echo "uploading docs to $packagename-$packageversion"
+docdir=$dist/doc/html
+cd "$docdir" || (echo "$docdir does not exist!"; exit 1)
+doc="$packagename-$packageversion-docs"
+echo -e "Compressing documentation from \033[1;34m$docdir\033[0m for \033[1;35m$packagename\033[0m-\033[1;33m$packageversion\033[1;30m"
+cp -r "$packagename" "$doc"
+tar -c -v -z --format=ustar -f "$doc.tar.gz" "$doc"
+echo -e "\033[1;32mUploading to Hackage...\033[0m"
+read -r -p "Hackage username: " username
+read -r -p "Hackage password: " -s password
+echo ""
+curl -X PUT -H 'Content-Type: application/x-tar' -H 'Content-Encoding: gzip' --data-binary "@$doc.tar.gz" "https://$username:$password@hackage.haskell.org/package/$packagename-$packageversion/docs" > /dev/null
+exit $?
